### PR TITLE
Feat: room creation/joining with synced users

### PR DESCRIPTION
**Pull request by captainexpo**
- Added Room and User class on the backend
- Can now create a room on the root page
- Assigns host to the user that created the room
- Can join room by going to /room/[id]?alias=<alias>&type=[guest|host]
- Users in room synced between everybody in the room

### CODE REVIEW

**Comment by Neko-22** [comment]
why are we allowing all origins??? i dont think its hard for us to set the origin

**Comment by Captainexpo-1** [comment]
Oh whoops, my bad

**Review by NeonGamerBot-QK — APPROVED** [review]

**Comment by Neko-22** [comment]
no worries lemme get set up and ill do it

**Comment by NeonGamerBot-QK** [comment]
> why are we allowing all origins??? i dont think its hard for us to set the origin

this, could you add a var which checks env for seeing if its in prod or test

**Comment by Captainexpo-1** [comment]
I can do it rq

**Comment by Neko-22** [comment]
ok
apoligies i cant git :pf:

**Comment by Neko-22** [comment]
uhhhhhhhhhhh where do we define FRONTEND_PORT?

**Comment by Neko-22** [comment]
oh .env.example ic ic

**Comment by Captainexpo-1** [comment]
Yeah you'll need to copy it and make a .env file

**Comment by Neko-22** [comment]
question: what does this code handle? if its for an end user wouldn't it be better for logs if we replaced 'Client' with alias or smthn?
```python
@app.websocket("/ws")
async def websocket_endpoint(websocket: WebSocket):
    await websocket.accept()
    try:
        while True:
            data = await websocket.receive_text()
            data = json.loads(data)
            await handle_message(websocket, data)
    except WebSocketDisconnect:
        print("Client disconnected")
```

**Comment by Neko-22** [comment]
my backend knowledge is not great so apologies if i completely misunderstand code

**Comment by Captainexpo-1** [comment]
That just listens for messages from the clients and handles them

**Comment by Captainexpo-1** [comment]
It would be good to make the alias show up in the logs, but right now I think it's fine because before a client disconnects they'll send a "leave-room" event.

**Comment by Neko-22** [comment]
i mean. adding an alias at the beginning of client side msgs to the logs is a good idea. i'll see what i can do

**Comment by Neko-22** [comment]
yep idk what the flip flap to do here :pf: system seems fine rn tho

**Comment by Captainexpo-1** [comment]
Cool, I can do the alias thing rq and then we're probably good to merge

**Comment by Captainexpo-1** [comment]
It should (?) work

**Review by prplwtf — APPROVED** [review]
I'm not a Python/back-end expert but LGTM!

**Pull request merged**
